name: RSS Update

on:
  schedule:
    - cron: "*/1 * * * *"   # 1分ごとに実行
  workflow_dispatch:         # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fetch RSS and generate index.html
        run: node rss-fetch.js

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update RSS feed" || echo "No changes to commit"
          git push
